version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: curanet-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/instance:/app/instance
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./frontend
    container_name: curanet-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
